language: python

python:
  - "3.6"
  
script:
  - python ENV_net.py
  - evaluate_performance.py
  - main.py
  - policy_net.py
  - ppo_agent.py
 
 before_install:
   - apt-get update
   - apt-get install libsdl2-gfx-dev libsdl2-ttf-dev

   - git clone -b v2.0.6 https://github.com/google-research/football.git
   - mkdir -p football/third_party/gfootball_engine/lib

   - wget https://storage.googleapis.com/gfootball/prebuilt_gameplayfootball_v2.0.6.so -O football/third_party/gfootball_engine/lib/prebuilt_gameplayfootball.so
   - cd football && GFOOTBALL_USE_PREBUILT_SO=1
 
 install:
   - pip install .
